export const eng = {
    bienvenida: 'Sign Language ASL/LSM',
    explora: 'Welcome to our American and Mexican Sign Language recognition and translation page, feel free to explore the page.',
    ls: 'America Sign Language (ASL)',
    inicio: 'Home',
    informacion: 'Information',
    acercade: "About us",
    lengua: 'Sign Language',
    sesion: 'Login',
    perfil: 'Profile',
    cuenta: 'My account',
    sesion2: 'Log out',
    limpiar: 'CLEAR',
    desplegar: 'SPLIT',
    resultLSM: 'LSM RESULT',
    predecir: 'PREDICT',
    lista: 'American Sign Language List',
    guardarletra: 'SAVE LETTER',
    resultASL: 'ASL RESULT',
    ls1: 'Mexican Sign Language',
    ls11: 'American Sign Language',
    traductor: 'Translator LSM/ASL',
    recoimg: 'Image recognition',
    recohand: 'Hand recognition',
    recuerdame: 'Remember me',
    olvidaste: 'Forgot your password?',
    notienescuenta: `Don't have an account yet? Sign up`,
    correo: 'Email',
    contra: 'Password',
    campor: 'Required field',
    correoinv: 'Invalid email',
    contracor: 'Password too short',
    contralar: 'Password too long',
    restablecer: 'Reset password',
    enviar: 'Submit',
    contrano: 'Passwords do not match',
    nombre: 'First name',
    apellido: 'Last name',
    fechanac: 'Birthdate',
    contrarep: 'Repeat password',
    registrarse: 'Sign up',
    yatienes: 'Do you already have an account? Login',
    res: 'Password reset',
    enviadores: 'Password reset link has been sent to your email:',
    compruebares: 'Check your inbox and click the link to reset your password',
    confirma: 'Confirm your email account',
    enviadocon: 'Confirmation link has been sent to your email:',
    compruebacon: 'Check your inbox and come back to login',
    confexito: 'Your password has been successfully reset',
    yapuedes: 'You can now log in with your new password!',
    newcontra: 'New password',
    newcontracon: 'Confirm new password',
    resta: 'Reset',
    bievenido: 'Welcome',
    cambiaridio: 'Cambiar idioma',
    empezar: 'Start',
    acercade1: 'Find out more about us',
    tec: 'Technological National of Mexico',
    personas: 'People who worked on the project:',
    lsm: "Mexican Sign Language",
    asl: "American Sign Language",
    aboutasl: "Learn more about american sign language (ASL, english acronym).",
    aboutlsm: "Learn more about mexican sign language (LSM, spanish acronym).",
    fed: "World Federation of the Deaf",
    aboutfed: "Learn more about of the world federation of the deaf.",
    saber: "Know more",
    derechos: "All rights reserved",
    infocuerpo: "Mexican Sign Language (LSM) is the language used by deaf people in Mexico. Like any language, it has its own syntax, grammar and lexicon. The human being today could not understand life without the ability to access the information that is being generated at all times in all areas. Oral communication is the most common way that allows human beings to participate in all environments of society, but when a person is born or acquires a hearing disability, it is impeded, the possibility of achieving true social fulfillment is reduced dramatically. important. The difficulty of people with hearing disabilities to communicate with others, hinders their educational, professional and human development, consequently their opportunities for inclusion are limited, given this need, deaf people have developed their own form of communication, the Language of Mexican Signs. However, although this allows them to communicate with each other, it does not always facilitate the relationship with the rest of the community, especially with listeners who do not know that language. The Mexican Sign Language is made up of visual signs with their own linguistic structure, with which deaf people in Mexico identify and express themselves. For the vast majority of those who were born deaf or have been deaf since childhood or youth, this is the language in which they articulate their thoughts and emotions, the one that allows them to satisfy their communicative needs as well as develop their cognitive abilities to the maximum while they interact with the world around them.",
    infofin: "Do you want to know more about sign language?",
    infoclic: "Click here!",
    infosub: "The difficulty of people with hearing disabilities to communicate with others hinders their educational, professional and human development, consequently their opportunities for inclusion are limited.",
    descrabout: 'We are students of the Technological Institute of Tijuana, of the Information Technology and Communications Engineering career, this project was carried out in order to make sign languages more known and to be able to practice them, it is part of our professional residence.',
    instrucciones: 'Instructions',
    uno: '1. Enter the word to be translated by image keyboard.',
    dos: '2. Click the button with the translate icon.',
    tres: '3. Click the split button.',
    cuatro: '4. Click the result button.',
    uno1: '1. Upload image to predict and click predict button.',
    dos2: '2. Once you have formed a word click on the translate button.',
    uno11: '1. Make the position with the hand of the desired letter and press save letter until a word is formed.',
}