export const esp = {
    bienvenida: 'Lengua de Señas LSM/ASL',
    explora: 'Sean bienvenidos a nuestro sitio para el reconocimiento y traducción de la lengua de señas mexicana y americana, siéntase libre de explorar la página.',
    ls: 'Lengua de Señas Mexicana (LSM)',
    inicio: 'Inicio',
    informacion: 'Información',
    traductor: 'Traductor LSM/ASL',
    acercade: 'Acerca de nosotros',
    lengua: 'Lengua De Señas',
    sesion: 'Iniciar sesión',
    perfil: 'Perfil',
    cuenta: 'Mi cuenta',
    sesion2: 'Cerrar sesión',
    limpiar: 'LIMPIAR',
    desplegar: 'DESPLEGAR',
    resultLSM: 'RESULTADO LSM',
    predecir: 'PREDECIR',
    lista: 'Lista de Lengua de Señas Americana',
    guardarletra: 'GUARDAR LETRA',
    resultASL: 'RESULTADO ASL',
    ls1: 'Lengua de Señas Mexicana',
    ls11: 'Lengua de Señas Americana',
    recoimg: 'Reconocimiento de imagen',
    recohand: 'Reconocimiento de mano',
    recuerdame: 'Recuérdame',
    olvidaste: 'Olvidaste tu contraseña?',
    notienescuenta: 'No tienes cuenta aún? Registrate',
    correo: 'Correo electrónico',
    contra: 'Contraseña',
    campor: 'Campo requerido',
    correoinv: 'Correo electrónico inválido',
    contracor: 'La contraseña es muy corta',
    contralar: 'La contraseña es muy larga',
    restablecer: 'Restablecer contraseña',
    enviar: 'Enviar',
    contrano: 'Las contraseñas no coinciden',
    nombre: 'Nombre(s)',
    apellido: 'Apellido(s)',
    fechanac: 'Fecha de nacimiento',
    contrarep: 'Repetir contraseña',
    registrarse: 'Registrarse',
    yatienes: 'Ya tienes cuenta? Inicia sesión',
    res: 'Restablecimiento de contraseña',
    enviadores: 'Se ha enviado el enlace para restablecer contraseña a tu correo electrónico:',
    compruebares: 'Comprueba tu bandeja de entrada y haz clic en el enlace para restablecer contraseña',
    confirma: 'Confirma tu cuenta de correo electrónico',
    enviadocon: 'Se ha enviado el enlace de confirmación a tu correo electrónico:',
    compruebacon: 'Comprueba tu bandeja de entrada y vuelve para iniciar sesión',
    confexito: 'Tu contraseña ha sido restablecida con éxito',
    yapuedes: 'Ya puedes iniciar sesión con tu nueva contrasena!',
    newcontra: 'Nueva contraseña',
    newcontracon: 'Confirmar nueva contraseña',
    resta: 'Restablecer',
    bievenido: 'Bienvenido',
    cambiaridio: 'Change language',
    empezar: 'Empezar',
    acercade1: 'Conoce más acerca de nosotros',
    tec: 'Tecnológico Nacional de México',
    personas: 'Personas que trabajaron en el proyecto:',
    lsm: "Lengua de Señas Mexicana",
    asl: "Lengua de Señas Americana",
    aboutasl: "Conoce más acerca de la lengua de señas americana (ASL, acrónimo en inglés).",
    aboutlsm: "Conoce más acerca de la lengua de señas mexicana (LSM, acrónimo en español).",
    fed: "Federación Mundial de Sordos",
    aboutfed: "Conoce más acerca de la federación mundial de sordos.",
    saber: "Saber más",
    derechos: "Todos los derechos reservados",
    infocuerpo: "La Lengua de Señas Mexicana (LSM), es la lengua que utilizan las personas sordas en México. Como toda lengua, posee su propia sintaxis, gramática y léxico. El ser humano en la actualidad no podría entender la vida sin la facultad de acceder a la información que a cada momento se está generando en los todos los ámbitos. La comunicación oral, es la forma más común que permite al ser humano participar en todos los entornos de la sociedad, pero cuando una persona nace o adquiere una discapacidad auditiva, se ve impedida, la posibilidad de alcanzar una verdadera realización social se reduce de manera importante. La dificultad de las personas con discapacidad auditiva para comunicarse con los demás, dificulta su desarrollo educativo, profesional y humano, por consecuencia se ven limitadas sus oportunidades de inclusión, ante esta necesidad, las personas sordas han desarrollado su propia forma de comunicación, la Lengua de Señas Mexicana. Sin embargo, aunque esta les permite comunicarse entre sí, no siempre facilita la relación con el resto de la comunidad, sobre todo, con los oyentes que desconocen esa lengua. La Lengua de Señas Mexicana, se compone de signos visuales con estructura lingüística propia, con la cual se identifican y expresan las personas sordas en México. Para la gran mayoría de quienes han nacido sordos o han quedado sordos desde la infancia o la juventud, ésta es la lengua en que articulan sus pensamientos y sus emociones, la que les permite satisfacer sus necesidades comunicativas así como desarrollar sus capacidades cognitivas al máximo mientras interactúan con el mundo que les rodea.",
    infofin: "Quieres conocer más acerca de la lengua de señas?",
    infoclic: "Haz clic aquí!",
    infosub: "La dificultad de las personas con discapacidad auditiva para comunicarse con los demás, dificulta su desarrollo educativo, profesional y humano, por consecuencia se ven limitadas sus oportunidades de inclusión.",
    descrabout: 'Somos estudiantes del Instituto Tecnológico de Tijuana, de la carrera de Ingeniería en Tecnologías de la Información y Comunicaciones, este proyecto se realizó con el fin de dar a conocer más las lenguas de señas y poder practicarlas, forma parte de nuestra residencia profesional.',
    instrucciones: 'Instrucciones',
    uno: '1. Introducir la palabra a traducir por teclado de imágenes.',
    dos: '2. Clic al botón con ícono de traducir.',
    tres: '3. Clic al botón de desplegar.',
    cuatro: '4. Clic al botón de resultado.',
    uno1: '1. Subir imagen a predecir y clic en botón predecir.',
    dos2: '2. Ya que haya formado una palabra clic al botón traducir.',
    uno11: '1. Hacer la posición con la mano de la letra deseada y dar en guardar letra hasta formar una palabra.',

}